### ISSUE TITLE
Code review: sobre um erro ao executar os testes

### ISSUE THREAD

**Issue by daneccc** [ayslana/ContentGiver#1]
https://github.com/ayslana/ContentGiver/blob/58175fc5c5ddc66e30704004b3df7493dd290607/ContentGiverTests/ArticleModelTests.swift#L37
https://github.com/ayslana/ContentGiver/blob/58175fc5c5ddc66e30704004b3df7493dd290607/ContentGiverTests/ArticleModelTests.swift#L44

Ao executar o projeto no XCode é apontado o seguinte erro nas duas linhas acima: "Cannot find 'ArticleModel' in scope". 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/39858223/197543816-37a5c2f3-9584-456f-a90e-f31f85146ef7.png">

Por alguma razão, o XCode não adiciona o model automaticamente ao Test Target. Acredito que uma solução para isso seria marcar os targets do ArticleModel manualmente. 

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/39858223/197544371-b6ce9925-9ca8-4fc1-beac-8fa293aa7fcc.png">

Feito isso, o XCode aponta outro erro: "Missing arguments for parameters 'articleUrl', 'image' in call", que poderia ser solucionado passando os parâmetros obrigatórios na chamada dessa struct.

**Comment by ayslana** [comment]
Fixed.
