### ISSUE TITLE
Code review: erro ao inicializar struct

### ISSUE THREAD

**Issue by Natalialocatelli** [ayslana/ContentGiver#2]
https://github.com/ayslana/ContentGiver/blob/58175fc5c5ddc66e30704004b3df7493dd290607/ContentGiverTests/ArticleModelTests.swift#L37
O Xcode está apontando um erro ao inicializar a struct articlemodel
<img width="826" alt="image" src="https://user-images.githubusercontent.com/92129189/197547385-e885ec0e-9e23-4730-9de0-623f26f3fa85.png">

Para solucionar seu problema sugiro o seguinte trecho   
```
 let instance = ArticleModel(author: "Author Test",
                       title: "Title Test",
                       description: "Description Test", 
                       articleUrl: "Url Test", 
                       image: "Image Test")
```

**Comment by ayslana** [comment]
Fixed.
